import type { ApplicantProfile, ApplicantsSortDirection, ApplicantsSortField } from './types'

export const DEFAULT_SORT_FIELD: ApplicantsSortField = 'score'
export const DEFAULT_SORT_DIRECTION: ApplicantsSortDirection = 'desc'

export const SORT_FIELD_BUTTONS: Array<{ value: ApplicantsSortField; label: string }> = [
  { value: 'score', label: 'By score' },
  { value: 'potential', label: 'Potential' },
  { value: 'motivation', label: 'Motivation' },
  { value: 'leadership', label: 'Leadership' },
  { value: 'experience', label: 'Experience' },
  { value: 'trust', label: 'Trust' },
]

export const MOCK_APPLICANT_PROFILES: ApplicantProfile[] = [
  {
    candidate_id: 'cand_001',
    candidate_name: 'Amina Beketova',
    program_name: 'Computer Science',
    scoring_run_id: 'run_20260328_001',
    scoring_version: 'v1.0.0',
    prompt_version: 'prompts_v3',
    eligibility_status: 'eligible',
    eligibility_reasons: [],
    merit_score: 74,
    confidence_score: 61,
    authenticity_risk: 43,
    recommendation: 'manual_review_required',
    review_flags: ['low_evidence_density', 'moderate_authenticity_risk'],
    merit_breakdown: {
      potential: 81,
      motivation: 84,
      leadership_agency: 68,
      experience_skills: 55,
      trust_completeness: 62,
    },
    feature_snapshot: {
      motivation_clarity: 0.84,
      initiative: 0.71,
      leadership_impact: 0.63,
      growth_trajectory: 0.79,
      resilience: 0.58,
      program_fit: 0.82,
      evidence_richness: 0.44,
      specificity_score: 0.49,
      evidence_count: 0.57,
      consistency_score: 0.74,
      completeness_score: 0.63,
      genericness_score: 0.41,
      contradiction_flag: false,
    },
    top_strengths: [
      'Clear motivation linked to the chosen program',
      'Strong signal of self-initiated activity',
      'Visible growth trajectory over time',
    ],
    main_gaps: ['Impact evidence is still limited', 'Several responses remain too general'],
    uncertainties: ['Leadership signal is present, but evidence density is moderate'],
    evidence_spans: [
      {
        dimension: 'motivation',
        source: 'essay',
        text: 'I want to build products that solve transport problems in my city...',
      },
      {
        dimension: 'initiative',
        source: 'bot_answer',
        text: 'I started a peer study group and organized weekly sessions...',
      },
    ],
    explanation: {
      summary:
        'Candidate shows strong motivation and growth potential, but confidence is only moderate because several claims are weakly supported by concrete evidence.',
      scoring_notes: {
        potential:
          'High because the profile contains clear signs of self-driven learning and upward trajectory.',
        motivation: 'High because goals are specific and connected to prior experience.',
        confidence: 'Moderate because evidence density is uneven across sections.',
      },
    },
  },
  {
    candidate_id: 'cand_002',
    candidate_name: 'Nursultan Omarov',
    program_name: 'Economics',
    scoring_run_id: 'run_20260328_002',
    scoring_version: 'v1.0.0',
    prompt_version: 'prompts_v3',
    eligibility_status: 'eligible',
    eligibility_reasons: [],
    merit_score: 88,
    confidence_score: 79,
    authenticity_risk: 28,
    recommendation: 'admit',
    review_flags: [],
    merit_breakdown: {
      potential: 86,
      motivation: 90,
      leadership_agency: 82,
      experience_skills: 79,
      trust_completeness: 84,
    },
    feature_snapshot: {
      motivation_clarity: 0.91,
      initiative: 0.86,
      leadership_impact: 0.76,
      growth_trajectory: 0.81,
      resilience: 0.72,
      program_fit: 0.9,
      evidence_richness: 0.83,
      specificity_score: 0.8,
      evidence_count: 0.77,
      consistency_score: 0.88,
      completeness_score: 0.85,
      genericness_score: 0.18,
      contradiction_flag: false,
    },
    top_strengths: [
      'Consistent and high-quality evidence across all sections',
      'Strong motivation with concrete goals and execution plan',
      'Leadership examples show clear measurable outcomes',
    ],
    main_gaps: ['Experience depth can be improved with longer-term projects'],
    uncertainties: ['No major uncertainties in current scoring run'],
    evidence_spans: [
      {
        dimension: 'leadership_impact',
        source: 'essay',
        text: 'Led a campus initiative that reduced waste by 25% in one semester.',
      },
      {
        dimension: 'program_fit',
        source: 'application_form',
        text: 'Selected economics track to build policy-focused analytical skills.',
      },
    ],
    explanation: {
      summary:
        'Candidate demonstrates strong readiness and high confidence with broad evidence support.',
      scoring_notes: {
        potential: 'High due to sustained growth and self-driven initiatives.',
        motivation: 'Very high due to clear goals and coherent rationale.',
        confidence: 'High because claims are specific and consistently supported.',
      },
    },
  },
  {
    candidate_id: 'cand_003',
    candidate_name: 'Mira Sadyk',
    program_name: 'Mathematics',
    scoring_run_id: 'run_20260328_003',
    scoring_version: 'v1.0.0',
    prompt_version: 'prompts_v3',
    eligibility_status: 'manual_review',
    eligibility_reasons: ['pending_english_certificate_validation'],
    merit_score: 82,
    confidence_score: 67,
    authenticity_risk: 35,
    recommendation: 'manual_review_required',
    review_flags: ['pending_document_verification'],
    merit_breakdown: {
      potential: 90,
      motivation: 76,
      leadership_agency: 70,
      experience_skills: 72,
      trust_completeness: 68,
    },
    feature_snapshot: {
      motivation_clarity: 0.74,
      initiative: 0.88,
      leadership_impact: 0.62,
      growth_trajectory: 0.87,
      resilience: 0.81,
      program_fit: 0.85,
      evidence_richness: 0.6,
      specificity_score: 0.64,
      evidence_count: 0.58,
      consistency_score: 0.69,
      completeness_score: 0.71,
      genericness_score: 0.3,
      contradiction_flag: false,
    },
    top_strengths: [
      'High growth trajectory in quantitative skills',
      'Strong initiative signals through independent research work',
    ],
    main_gaps: ['Some evidence references require document verification'],
    uncertainties: ['Language certificate authenticity is pending confirmation'],
    evidence_spans: [
      {
        dimension: 'growth_trajectory',
        source: 'essay',
        text: 'Moved from basic olympiad participation to national-level finals in two years.',
      },
    ],
    explanation: {
      summary:
        'Strong mathematical potential with good evidence, but final eligibility requires manual checks.',
      scoring_notes: {
        potential: 'Very high due to sustained learning acceleration.',
        confidence: 'Moderate-high pending external document verification.',
      },
    },
  },
  {
    candidate_id: 'cand_004',
    candidate_name: 'Arman Iskakov',
    program_name: 'Information Systems',
    scoring_run_id: 'run_20260328_004',
    scoring_version: 'v1.0.0',
    prompt_version: 'prompts_v3',
    eligibility_status: 'eligible',
    eligibility_reasons: [],
    merit_score: 79,
    confidence_score: 73,
    authenticity_risk: 31,
    recommendation: 'admit',
    review_flags: [],
    merit_breakdown: {
      potential: 78,
      motivation: 81,
      leadership_agency: 75,
      experience_skills: 83,
      trust_completeness: 80,
    },
    feature_snapshot: {
      motivation_clarity: 0.79,
      initiative: 0.74,
      leadership_impact: 0.7,
      growth_trajectory: 0.72,
      resilience: 0.69,
      program_fit: 0.84,
      evidence_richness: 0.71,
      specificity_score: 0.68,
      evidence_count: 0.66,
      consistency_score: 0.8,
      completeness_score: 0.77,
      genericness_score: 0.22,
      contradiction_flag: false,
    },
    top_strengths: [
      'Balanced profile with consistent quality',
      'Strong practical systems experience',
    ],
    main_gaps: ['Leadership impact examples could include stronger quantitative evidence'],
    uncertainties: [],
    evidence_spans: [
      {
        dimension: 'experience_skills',
        source: 'bot_answer',
        text: 'Built and deployed a student ERP prototype used by 120+ users.',
      },
    ],
    explanation: {
      summary: 'Reliable candidate with balanced strengths and low risk profile.',
      scoring_notes: {
        experience: 'High due to demonstrated project execution.',
        trust: 'High due to internal consistency and document completeness.',
      },
    },
  },
  {
    candidate_id: 'cand_005',
    candidate_name: 'Diana Tulegen',
    program_name: 'Data Science',
    scoring_run_id: 'run_20260328_005',
    scoring_version: 'v1.0.0',
    prompt_version: 'prompts_v3',
    eligibility_status: 'eligible',
    eligibility_reasons: [],
    merit_score: 85,
    confidence_score: 72,
    authenticity_risk: 39,
    recommendation: 'manual_review_required',
    review_flags: ['moderate_authenticity_risk'],
    merit_breakdown: {
      potential: 88,
      motivation: 80,
      leadership_agency: 73,
      experience_skills: 77,
      trust_completeness: 71,
    },
    feature_snapshot: {
      motivation_clarity: 0.78,
      initiative: 0.83,
      leadership_impact: 0.69,
      growth_trajectory: 0.86,
      resilience: 0.74,
      program_fit: 0.88,
      evidence_richness: 0.57,
      specificity_score: 0.61,
      evidence_count: 0.55,
      consistency_score: 0.7,
      completeness_score: 0.73,
      genericness_score: 0.33,
      contradiction_flag: false,
    },
    top_strengths: ['Strong technical potential and learning velocity'],
    main_gaps: ['Evidence for leadership outcomes is moderate'],
    uncertainties: ['Authenticity score should be monitored in next scoring run'],
    evidence_spans: [
      {
        dimension: 'initiative',
        source: 'essay',
        text: 'Created a mentoring circle for beginners in machine learning.',
      },
    ],
    explanation: {
      summary:
        'High merit candidate with notable potential, but confidence is moderate due to evidence density.',
      scoring_notes: {
        potential: 'High due to rapid progress and self-led work.',
        confidence: 'Moderate pending denser evidence in leadership examples.',
      },
    },
  },
  {
    candidate_id: 'cand_006',
    candidate_name: 'Yerzhan Kosherbay',
    program_name: 'Physics',
    scoring_run_id: 'run_20260328_006',
    scoring_version: 'v1.0.0',
    prompt_version: 'prompts_v3',
    eligibility_status: 'eligible',
    eligibility_reasons: [],
    merit_score: 70,
    confidence_score: 64,
    authenticity_risk: 37,
    recommendation: 'manual_review_required',
    review_flags: ['low_evidence_density'],
    merit_breakdown: {
      potential: 75,
      motivation: 69,
      leadership_agency: 72,
      experience_skills: 66,
      trust_completeness: 65,
    },
    feature_snapshot: {
      motivation_clarity: 0.67,
      initiative: 0.65,
      leadership_impact: 0.71,
      growth_trajectory: 0.73,
      resilience: 0.76,
      program_fit: 0.7,
      evidence_richness: 0.47,
      specificity_score: 0.52,
      evidence_count: 0.44,
      consistency_score: 0.68,
      completeness_score: 0.69,
      genericness_score: 0.34,
      contradiction_flag: false,
    },
    top_strengths: ['Good resilience signal and stable growth trend'],
    main_gaps: ['Impact examples need stronger quantified outcomes'],
    uncertainties: ['Program fit might improve with clearer specialization intent'],
    evidence_spans: [
      {
        dimension: 'resilience',
        source: 'bot_answer',
        text: 'Repeatedly improved competition results after failed attempts.',
      },
    ],
    explanation: {
      summary:
        'Candidate has acceptable merit and potential, but evidence density limits confidence.',
      scoring_notes: {
        potential: 'Moderately high with visible growth trajectory.',
        confidence: 'Moderate due to sparse concrete evidence.',
      },
    },
  },
  {
    candidate_id: 'cand_007',
    candidate_name: 'Aigerim Kurmangali',
    program_name: 'Cybersecurity',
    scoring_run_id: 'run_20260328_007',
    scoring_version: 'v1.0.0',
    prompt_version: 'prompts_v3',
    eligibility_status: 'ineligible',
    eligibility_reasons: ['missing_required_certificate'],
    merit_score: 67,
    confidence_score: 58,
    authenticity_risk: 29,
    recommendation: 'reject',
    review_flags: ['eligibility_not_met'],
    merit_breakdown: {
      potential: 79,
      motivation: 77,
      leadership_agency: 61,
      experience_skills: 58,
      trust_completeness: 52,
    },
    feature_snapshot: {
      motivation_clarity: 0.76,
      initiative: 0.73,
      leadership_impact: 0.57,
      growth_trajectory: 0.74,
      resilience: 0.68,
      program_fit: 0.79,
      evidence_richness: 0.51,
      specificity_score: 0.56,
      evidence_count: 0.49,
      consistency_score: 0.62,
      completeness_score: 0.48,
      genericness_score: 0.31,
      contradiction_flag: false,
    },
    top_strengths: ['Strong motivation for cybersecurity specialization'],
    main_gaps: ['Mandatory eligibility requirement not satisfied'],
    uncertainties: ['Can be reconsidered once missing certificate is provided'],
    evidence_spans: [
      {
        dimension: 'program_fit',
        source: 'essay',
        text: 'Describes clear specialization path in defensive security.',
      },
    ],
    explanation: {
      summary:
        'Merit is moderate, but candidate is currently ineligible due to missing required documents.',
      scoring_notes: {
        trust: 'Lower due to incomplete document package.',
      },
    },
  },
  {
    candidate_id: 'cand_008',
    candidate_name: 'Madina Akhmetova',
    program_name: 'Business Analytics',
    scoring_run_id: 'run_20260328_008',
    scoring_version: 'v1.0.0',
    prompt_version: 'prompts_v3',
    eligibility_status: 'eligible',
    eligibility_reasons: [],
    merit_score: 76,
    confidence_score: 70,
    authenticity_risk: 24,
    recommendation: 'admit',
    review_flags: [],
    merit_breakdown: {
      potential: 74,
      motivation: 79,
      leadership_agency: 71,
      experience_skills: 75,
      trust_completeness: 78,
    },
    feature_snapshot: {
      motivation_clarity: 0.78,
      initiative: 0.69,
      leadership_impact: 0.66,
      growth_trajectory: 0.7,
      resilience: 0.72,
      program_fit: 0.81,
      evidence_richness: 0.68,
      specificity_score: 0.64,
      evidence_count: 0.63,
      consistency_score: 0.77,
      completeness_score: 0.8,
      genericness_score: 0.2,
      contradiction_flag: false,
    },
    top_strengths: ['Good trust/completeness and balanced profile'],
    main_gaps: ['Potential score could improve with stronger growth evidence'],
    uncertainties: [],
    evidence_spans: [
      {
        dimension: 'trust_completeness',
        source: 'application_form',
        text: 'All required fields and references are filled and consistent.',
      },
    ],
    explanation: {
      summary: 'Solid balanced candidate with strong trust and adequate merit.',
      scoring_notes: {
        trust: 'High due to complete and consistent submission package.',
      },
    },
  },
]
