import type { ApplicantProfile } from './types'

export const MOCK_APPLICANT_PROFILES: ApplicantProfile[] = [
  {
    candidate_id: 'cand_001',
    candidate_name: 'Amina Beketova',
    program_name: 'Computer Science',
    scoring_run_id: 'run_20260328_001',
    scoring_version: 'v1.2.0',
    eligibility_status: 'eligible',
    eligibility_reasons: [],
    merit_score: 74,
    confidence_score: 61,
    authenticity_risk: 43,
    recommendation: 'manual_review_required',
    review_flags: ['low_evidence_density', 'moderate_authenticity_risk'],
    hidden_potential_score: 58,
    support_needed_score: 42,
    shortlist_priority_score: 65,
    evidence_coverage_score: 44,
    trajectory_score: 79,
    top_strengths: [
      'Clear motivation linked to the chosen program',
      'Strong signal of self-initiated activity',
      'Visible growth trajectory over time',
    ],
    main_gaps: ['Impact evidence is still limited', 'Several responses remain too general'],
    committee_cohorts: ['Moderate evidence density', 'Authenticity review needed'],
    why_candidate_surfaced: [],
    what_to_verify_manually: [
      'Ask for concrete examples of the peer study group outcomes.',
      'Verify self-reported initiative claims with references.',
    ],
    suggested_follow_up_question:
      'Can you describe a specific problem you solved in your study group and what the outcome was?',
    evidence_highlights: [
      {
        claim: 'I want to build products that solve transport problems in my city',
        support_level: 'moderate',
        source: 'motivation_letter_text',
        snippet: 'I want to build products that solve transport problems in my city...',
        support_score: 0.6,
        rationale: 'Goal is clear but lacks concrete steps or prior experience in transport tech.',
      },
      {
        claim: 'Started a peer study group',
        support_level: 'weak',
        source: 'motivation_questions',
        snippet: 'I started a peer study group and organized weekly sessions...',
        support_score: 0.4,
        rationale: 'Claim is present but no measurable outcomes reported.',
      },
    ],
    explanation: {
      summary:
        'Candidate shows strong motivation and growth potential, but confidence is only moderate because several claims are weakly supported by concrete evidence.',
      scoring_notes: {
        potential: 'High because the profile contains clear signs of self-driven learning.',
        motivation: 'High because goals are specific and connected to prior experience.',
        confidence: 'Moderate because evidence density is uneven across sections.',
      },
    },
  },
  {
    candidate_id: 'cand_002',
    candidate_name: 'Nursultan Omarov',
    program_name: 'Economics',
    scoring_run_id: 'run_20260328_002',
    scoring_version: 'v1.2.0',
    eligibility_status: 'eligible',
    eligibility_reasons: [],
    merit_score: 88,
    confidence_score: 79,
    authenticity_risk: 28,
    recommendation: 'standard_review',
    review_flags: [],
    hidden_potential_score: 65,
    support_needed_score: 20,
    shortlist_priority_score: 88,
    evidence_coverage_score: 83,
    trajectory_score: 81,
    top_strengths: [
      'Consistent and high-quality evidence across all sections',
      'Strong motivation with concrete goals and execution plan',
      'Leadership examples show clear measurable outcomes',
    ],
    main_gaps: ['Experience depth can be improved with longer-term projects'],
    committee_cohorts: ['Strong overall candidate'],
    why_candidate_surfaced: ['High merit with strong evidence density'],
    what_to_verify_manually: ['Confirm campus waste reduction statistics with institution.'],
    suggested_follow_up_question:
      'What were the biggest challenges you faced while leading the campus waste initiative?',
    evidence_highlights: [
      {
        claim: 'Led campus waste reduction initiative',
        support_level: 'strong',
        source: 'motivation_letter_text',
        snippet: 'Led a campus initiative that reduced waste by 25% in one semester.',
        support_score: 0.85,
        rationale: 'Specific measurable outcome with clear leadership role.',
      },
    ],
    explanation: {
      summary:
        'Candidate demonstrates strong readiness and high confidence with broad evidence support.',
      scoring_notes: {
        potential: 'High due to sustained growth and self-driven initiatives.',
        motivation: 'Very high due to clear goals and coherent rationale.',
        confidence: 'High because claims are specific and consistently supported.',
      },
    },
  },
  {
    candidate_id: 'cand_003',
    candidate_name: 'Mira Sadyk',
    program_name: 'Mathematics',
    scoring_run_id: 'run_20260328_003',
    scoring_version: 'v1.2.0',
    eligibility_status: 'conditionally_eligible',
    eligibility_reasons: ['pending_english_certificate_validation'],
    merit_score: 82,
    confidence_score: 67,
    authenticity_risk: 35,
    recommendation: 'review_priority',
    review_flags: ['eligibility_gate'],
    hidden_potential_score: 72,
    support_needed_score: 35,
    shortlist_priority_score: 78,
    evidence_coverage_score: 60,
    trajectory_score: 87,
    top_strengths: [
      'High growth trajectory in quantitative skills',
      'Strong initiative signals through independent research work',
    ],
    main_gaps: ['Some evidence references require document verification'],
    committee_cohorts: ['High potential with eligibility gate'],
    why_candidate_surfaced: [],
    what_to_verify_manually: [
      'Confirm English certificate status.',
      'Validate olympiad participation records.',
    ],
    suggested_follow_up_question:
      'Can you provide documentation for your national-level olympiad results?',
    evidence_highlights: [
      {
        claim: 'National-level olympiad finalist',
        support_level: 'moderate',
        source: 'motivation_letter_text',
        snippet: 'Moved from basic olympiad participation to national-level finals in two years.',
        support_score: 0.6,
        rationale: 'Trajectory is impressive but external verification needed.',
      },
    ],
    explanation: {
      summary:
        'Strong mathematical potential with good evidence, but final eligibility requires manual checks.',
      scoring_notes: {
        potential: 'Very high due to sustained learning acceleration.',
        confidence: 'Moderate-high pending external document verification.',
      },
    },
  },
  {
    candidate_id: 'cand_004',
    candidate_name: 'Arman Iskakov',
    program_name: 'Information Systems',
    scoring_run_id: 'run_20260328_004',
    scoring_version: 'v1.2.0',
    eligibility_status: 'eligible',
    eligibility_reasons: [],
    merit_score: 79,
    confidence_score: 73,
    authenticity_risk: 31,
    recommendation: 'standard_review',
    review_flags: [],
    hidden_potential_score: 55,
    support_needed_score: 25,
    shortlist_priority_score: 75,
    evidence_coverage_score: 71,
    trajectory_score: 72,
    top_strengths: [
      'Balanced profile with consistent quality',
      'Strong practical systems experience',
    ],
    main_gaps: ['Leadership impact examples could include stronger quantitative evidence'],
    committee_cohorts: ['Balanced practical candidate'],
    why_candidate_surfaced: [],
    what_to_verify_manually: ['Confirm ERP project user count with school administration.'],
    suggested_follow_up_question:
      'How did you handle the technical challenges when deploying your ERP prototype?',
    evidence_highlights: [
      {
        claim: 'Built student ERP prototype',
        support_level: 'strong',
        source: 'motivation_questions',
        snippet: 'Built and deployed a student ERP prototype used by 120+ users.',
        support_score: 0.8,
        rationale: 'Specific user count and deployment claim.',
      },
    ],
    explanation: {
      summary: 'Reliable candidate with balanced strengths and low risk profile.',
      scoring_notes: {
        potential: 'Solid due to demonstrated project execution.',
        confidence: 'High due to internal consistency and document completeness.',
      },
    },
  },
  {
    candidate_id: 'cand_005',
    candidate_name: 'Diana Tulegen',
    program_name: 'Data Science',
    scoring_run_id: 'run_20260328_005',
    scoring_version: 'v1.2.0',
    eligibility_status: 'eligible',
    eligibility_reasons: [],
    merit_score: 85,
    confidence_score: 72,
    authenticity_risk: 39,
    recommendation: 'manual_review_required',
    review_flags: ['moderate_authenticity_risk'],
    hidden_potential_score: 70,
    support_needed_score: 30,
    shortlist_priority_score: 80,
    evidence_coverage_score: 57,
    trajectory_score: 86,
    top_strengths: ['Strong technical potential and learning velocity'],
    main_gaps: ['Evidence for leadership outcomes is moderate'],
    committee_cohorts: ['Authenticity review needed'],
    why_candidate_surfaced: [],
    what_to_verify_manually: [
      'Ask for details about the mentoring circle for ML beginners.',
      'Request portfolio or project links for technical claims.',
    ],
    suggested_follow_up_question:
      'Can you share a specific project from your mentoring circle and describe what participants built?',
    evidence_highlights: [
      {
        claim: 'Created ML mentoring circle',
        support_level: 'moderate',
        source: 'motivation_letter_text',
        snippet: 'Created a mentoring circle for beginners in machine learning.',
        support_score: 0.55,
        rationale: 'Initiative is clear but outcomes and scale are not documented.',
      },
    ],
    explanation: {
      summary:
        'High merit candidate with notable potential, but confidence is moderate due to evidence density.',
      scoring_notes: {
        potential: 'High due to rapid progress and self-led work.',
        confidence: 'Moderate pending denser evidence in leadership examples.',
      },
    },
  },
]
