import type { ApplicantProfile } from './types'

export const MOCK_APPLICANT_PROFILES: ApplicantProfile[] = [
  {
    candidate_id: 'cand_001',
    candidate_name: 'Amina Beketova',
    program_name: 'Computer Science',
    scoring_run_id: 'run_20260328_001',
    scoring_version: 'v1.2.0',
    prompt_version: null,
    extraction_mode: 'deterministic_scoring',
    extractor_version: 'llm-extractor-v1',
    llm_metadata: { provider: 'openai-compatible', model: 'llama3.1:8b', latency_ms: 54320 },
    eligibility_status: 'eligible',
    eligibility_reasons: [],
    merit_score: 74,
    confidence_score: 61,
    authenticity_risk: 43,
    recommendation: 'manual_review_required',
    review_flags: ['low_evidence_density', 'moderate_authenticity_risk'],
    merit_breakdown: {
      potential: 81,
      motivation: 84,
      leadership_agency: 68,
      experience_skills: 55,
      trust_completeness: 62,
    },
    feature_snapshot: {
      motivation_clarity: 0.84,
      initiative: 0.71,
      leadership_impact: 0.63,
      growth_trajectory: 0.79,
      resilience: 0.58,
      program_fit: 0.82,
      evidence_richness: 0.44,
      specificity_score: 0.49,
      evidence_count: 0.57,
      consistency_score: 0.74,
      completeness_score: 0.63,
      genericness_score: 0.41,
      contradiction_flag: false,
      docs_count_score: 0.5,
      portfolio_links_score: 0.25,
      has_video_presentation: false,
      logical_source_groups_present: 2,
      material_support_score: 0.48,
      polished_but_empty_score: 0.35,
      cross_section_mismatch_score: 0.08,
      authenticity_risk_raw: 0.43,
      ai_detector_probability: 0.52,
      ai_detector_applicable: true,
      excluded_sensitive_fields_count: 0,
    },
    semantic_rubric_scores: {
      leadership_potential: 62,
      growth_trajectory: 68,
      motivation_authenticity: 71,
      authenticity_groundedness: 55,
      hidden_potential: 58,
    },
    top_strengths: [
      'Clear motivation linked to the chosen program',
      'Strong signal of self-initiated activity',
      'Visible growth trajectory over time',
    ],
    main_gaps: ['Impact evidence is still limited', 'Several responses remain too general'],
    uncertainties: ['Leadership signal is present, but evidence density is moderate'],
    authenticity_review_reasons: [
      'Claims are under-supported by concrete actions, examples, or outcomes.',
    ],
    ai_detector: {
      enabled: true,
      applicable: true,
      language: 'en',
      probability_ai_generated: 0.52,
      provider: 'huggingface-local',
      model: 'desklib/ai-text-detector-v1.01',
      note: 'ok',
    },
    committee_cohorts: ['Moderate evidence density', 'Authenticity review needed'],
    why_candidate_surfaced: [],
    what_to_verify_manually: [
      'Ask for concrete examples of the peer study group outcomes.',
      'Verify self-reported initiative claims with references.',
    ],
    suggested_follow_up_question:
      'Can you describe a specific problem you solved in your study group and what the outcome was?',
    evidence_spans: [
      {
        source: 'motivation_letter_text',
        snippet: 'I want to build products that solve transport problems in my city...',
      },
      {
        source: 'motivation_questions',
        snippet: 'I started a peer study group and organized weekly sessions...',
      },
    ],
    explanation: {
      summary:
        'Candidate shows strong motivation and growth potential, but confidence is only moderate because several claims are weakly supported by concrete evidence.',
      scoring_notes: {
        potential:
          'High because the profile contains clear signs of self-driven learning and upward trajectory.',
        motivation: 'High because goals are specific and connected to prior experience.',
        confidence: 'Moderate because evidence density is uneven across sections.',
      },
    },
  },
  {
    candidate_id: 'cand_002',
    candidate_name: 'Nursultan Omarov',
    program_name: 'Economics',
    scoring_run_id: 'run_20260328_002',
    scoring_version: 'v1.2.0',
    prompt_version: null,
    extraction_mode: 'deterministic_scoring',
    extractor_version: 'llm-extractor-v1',
    llm_metadata: { provider: 'openai-compatible', model: 'llama3.1:8b', latency_ms: 47890 },
    eligibility_status: 'eligible',
    eligibility_reasons: [],
    merit_score: 88,
    confidence_score: 79,
    authenticity_risk: 28,
    recommendation: 'standard_review',
    review_flags: [],
    merit_breakdown: {
      potential: 86,
      motivation: 90,
      leadership_agency: 82,
      experience_skills: 79,
      trust_completeness: 84,
    },
    feature_snapshot: {
      motivation_clarity: 0.91,
      initiative: 0.86,
      leadership_impact: 0.76,
      growth_trajectory: 0.81,
      resilience: 0.72,
      program_fit: 0.9,
      evidence_richness: 0.83,
      specificity_score: 0.8,
      evidence_count: 0.77,
      consistency_score: 0.88,
      completeness_score: 0.85,
      genericness_score: 0.18,
      contradiction_flag: false,
      docs_count_score: 0.6667,
      portfolio_links_score: 0.5,
      has_video_presentation: true,
      logical_source_groups_present: 4,
      material_support_score: 0.78,
      polished_but_empty_score: 0.12,
      cross_section_mismatch_score: 0.02,
      authenticity_risk_raw: 0.28,
      ai_detector_probability: 0.21,
      ai_detector_applicable: true,
      excluded_sensitive_fields_count: 0,
    },
    semantic_rubric_scores: {
      leadership_potential: 74,
      growth_trajectory: 72,
      motivation_authenticity: 78,
      authenticity_groundedness: 70,
      hidden_potential: 65,
    },
    top_strengths: [
      'Consistent and high-quality evidence across all sections',
      'Strong motivation with concrete goals and execution plan',
      'Leadership examples show clear measurable outcomes',
    ],
    main_gaps: ['Experience depth can be improved with longer-term projects'],
    uncertainties: ['No major uncertainties in current scoring run'],
    authenticity_review_reasons: [],
    ai_detector: {
      enabled: true,
      applicable: true,
      language: 'en',
      probability_ai_generated: 0.21,
      provider: 'huggingface-local',
      model: 'desklib/ai-text-detector-v1.01',
      note: 'ok',
    },
    committee_cohorts: ['Strong overall candidate'],
    why_candidate_surfaced: ['High merit with strong evidence density'],
    what_to_verify_manually: ['Confirm campus waste reduction statistics with institution.'],
    suggested_follow_up_question:
      'What were the biggest challenges you faced while leading the campus waste initiative?',
    evidence_spans: [
      {
        source: 'motivation_letter_text',
        snippet: 'Led a campus initiative that reduced waste by 25% in one semester.',
      },
      {
        source: 'application_form',
        snippet: 'Selected economics track to build policy-focused analytical skills.',
      },
    ],
    explanation: {
      summary:
        'Candidate demonstrates strong readiness and high confidence with broad evidence support.',
      scoring_notes: {
        potential: 'High due to sustained growth and self-driven initiatives.',
        motivation: 'Very high due to clear goals and coherent rationale.',
        confidence: 'High because claims are specific and consistently supported.',
      },
    },
  },
  {
    candidate_id: 'cand_003',
    candidate_name: 'Mira Sadyk',
    program_name: 'Mathematics',
    scoring_run_id: 'run_20260328_003',
    scoring_version: 'v1.2.0',
    prompt_version: null,
    extraction_mode: 'deterministic_scoring',
    extractor_version: 'llm-extractor-v1',
    llm_metadata: { provider: 'openai-compatible', model: 'llama3.1:8b', latency_ms: 61200 },
    eligibility_status: 'conditionally_eligible',
    eligibility_reasons: ['pending_english_certificate_validation'],
    merit_score: 82,
    confidence_score: 67,
    authenticity_risk: 35,
    recommendation: 'review_priority',
    review_flags: ['eligibility_gate'],
    merit_breakdown: {
      potential: 90,
      motivation: 76,
      leadership_agency: 70,
      experience_skills: 72,
      trust_completeness: 68,
    },
    feature_snapshot: {
      motivation_clarity: 0.74,
      initiative: 0.88,
      leadership_impact: 0.62,
      growth_trajectory: 0.87,
      resilience: 0.81,
      program_fit: 0.85,
      evidence_richness: 0.6,
      specificity_score: 0.64,
      evidence_count: 0.58,
      consistency_score: 0.69,
      completeness_score: 0.71,
      genericness_score: 0.3,
      contradiction_flag: false,
      docs_count_score: 0.3333,
      portfolio_links_score: 0.0,
      has_video_presentation: false,
      logical_source_groups_present: 2,
      material_support_score: 0.55,
      polished_but_empty_score: 0.22,
      cross_section_mismatch_score: 0.05,
      authenticity_risk_raw: 0.35,
      ai_detector_probability: 0.38,
      ai_detector_applicable: true,
      excluded_sensitive_fields_count: 0,
    },
    semantic_rubric_scores: {
      leadership_potential: 60,
      growth_trajectory: 75,
      motivation_authenticity: 63,
      authenticity_groundedness: 58,
      hidden_potential: 72,
    },
    top_strengths: [
      'High growth trajectory in quantitative skills',
      'Strong initiative signals through independent research work',
    ],
    main_gaps: ['Some evidence references require document verification'],
    uncertainties: ['Language certificate authenticity is pending confirmation'],
    authenticity_review_reasons: [],
    ai_detector: {
      enabled: true,
      applicable: true,
      language: 'en',
      probability_ai_generated: 0.38,
      provider: 'huggingface-local',
      model: 'desklib/ai-text-detector-v1.01',
      note: 'ok',
    },
    committee_cohorts: ['High potential with eligibility gate'],
    why_candidate_surfaced: [],
    what_to_verify_manually: [
      'Confirm English certificate status.',
      'Validate olympiad participation records.',
    ],
    suggested_follow_up_question:
      'Can you provide documentation for your national-level olympiad results?',
    evidence_spans: [
      {
        source: 'motivation_letter_text',
        snippet: 'Moved from basic olympiad participation to national-level finals in two years.',
      },
    ],
    explanation: {
      summary:
        'Strong mathematical potential with good evidence, but final eligibility requires manual checks.',
      scoring_notes: {
        potential: 'Very high due to sustained learning acceleration.',
        confidence: 'Moderate-high pending external document verification.',
      },
    },
  },
  {
    candidate_id: 'cand_004',
    candidate_name: 'Arman Iskakov',
    program_name: 'Information Systems',
    scoring_run_id: 'run_20260328_004',
    scoring_version: 'v1.2.0',
    prompt_version: null,
    extraction_mode: 'deterministic_scoring',
    extractor_version: 'llm-extractor-v1',
    llm_metadata: { provider: 'openai-compatible', model: 'llama3.1:8b', latency_ms: 43150 },
    eligibility_status: 'eligible',
    eligibility_reasons: [],
    merit_score: 79,
    confidence_score: 73,
    authenticity_risk: 31,
    recommendation: 'standard_review',
    review_flags: [],
    merit_breakdown: {
      potential: 78,
      motivation: 81,
      leadership_agency: 75,
      experience_skills: 83,
      trust_completeness: 80,
    },
    feature_snapshot: {
      motivation_clarity: 0.79,
      initiative: 0.74,
      leadership_impact: 0.7,
      growth_trajectory: 0.72,
      resilience: 0.69,
      program_fit: 0.84,
      evidence_richness: 0.71,
      specificity_score: 0.68,
      evidence_count: 0.66,
      consistency_score: 0.8,
      completeness_score: 0.77,
      genericness_score: 0.22,
      contradiction_flag: false,
      docs_count_score: 0.5,
      portfolio_links_score: 0.75,
      has_video_presentation: true,
      logical_source_groups_present: 3,
      material_support_score: 0.72,
      polished_but_empty_score: 0.15,
      cross_section_mismatch_score: 0.03,
      authenticity_risk_raw: 0.31,
      ai_detector_probability: 0.18,
      ai_detector_applicable: true,
      excluded_sensitive_fields_count: 0,
    },
    semantic_rubric_scores: {
      leadership_potential: 66,
      growth_trajectory: 62,
      motivation_authenticity: 69,
      authenticity_groundedness: 68,
      hidden_potential: 55,
    },
    top_strengths: [
      'Balanced profile with consistent quality',
      'Strong practical systems experience',
    ],
    main_gaps: ['Leadership impact examples could include stronger quantitative evidence'],
    uncertainties: [],
    authenticity_review_reasons: [],
    ai_detector: {
      enabled: true,
      applicable: true,
      language: 'en',
      probability_ai_generated: 0.18,
      provider: 'huggingface-local',
      model: 'desklib/ai-text-detector-v1.01',
      note: 'ok',
    },
    committee_cohorts: ['Balanced practical candidate'],
    why_candidate_surfaced: [],
    what_to_verify_manually: ['Confirm ERP project user count with school administration.'],
    suggested_follow_up_question:
      'How did you handle the technical challenges when deploying your ERP prototype?',
    evidence_spans: [
      {
        source: 'motivation_questions',
        snippet: 'Built and deployed a student ERP prototype used by 120+ users.',
      },
    ],
    explanation: {
      summary: 'Reliable candidate with balanced strengths and low risk profile.',
      scoring_notes: {
        potential: 'Solid due to demonstrated project execution.',
        confidence: 'High due to internal consistency and document completeness.',
      },
    },
  },
  {
    candidate_id: 'cand_005',
    candidate_name: 'Diana Tulegen',
    program_name: 'Data Science',
    scoring_run_id: 'run_20260328_005',
    scoring_version: 'v1.2.0',
    prompt_version: null,
    extraction_mode: 'deterministic_scoring',
    extractor_version: 'llm-extractor-v1',
    llm_metadata: { provider: 'openai-compatible', model: 'llama3.1:8b', latency_ms: 58740 },
    eligibility_status: 'eligible',
    eligibility_reasons: [],
    merit_score: 85,
    confidence_score: 72,
    authenticity_risk: 39,
    recommendation: 'manual_review_required',
    review_flags: ['moderate_authenticity_risk'],
    merit_breakdown: {
      potential: 88,
      motivation: 80,
      leadership_agency: 73,
      experience_skills: 77,
      trust_completeness: 71,
    },
    feature_snapshot: {
      motivation_clarity: 0.78,
      initiative: 0.83,
      leadership_impact: 0.69,
      growth_trajectory: 0.86,
      resilience: 0.74,
      program_fit: 0.88,
      evidence_richness: 0.57,
      specificity_score: 0.61,
      evidence_count: 0.55,
      consistency_score: 0.7,
      completeness_score: 0.73,
      genericness_score: 0.33,
      contradiction_flag: false,
      docs_count_score: 0.3333,
      portfolio_links_score: 0.5,
      has_video_presentation: false,
      logical_source_groups_present: 3,
      material_support_score: 0.52,
      polished_but_empty_score: 0.38,
      cross_section_mismatch_score: 0.04,
      authenticity_risk_raw: 0.39,
      ai_detector_probability: 0.61,
      ai_detector_applicable: true,
      excluded_sensitive_fields_count: 0,
    },
    semantic_rubric_scores: {
      leadership_potential: 58,
      growth_trajectory: 73,
      motivation_authenticity: 65,
      authenticity_groundedness: 52,
      hidden_potential: 70,
    },
    top_strengths: ['Strong technical potential and learning velocity'],
    main_gaps: ['Evidence for leadership outcomes is moderate'],
    uncertainties: ['Authenticity score should be monitored in next scoring run'],
    authenticity_review_reasons: [
      'Auxiliary English-only AI detector assigned elevated AI-likeness; treat this only as a manual review signal.',
    ],
    ai_detector: {
      enabled: true,
      applicable: true,
      language: 'en',
      probability_ai_generated: 0.61,
      provider: 'huggingface-local',
      model: 'desklib/ai-text-detector-v1.01',
      note: 'ok',
    },
    committee_cohorts: ['Authenticity review needed'],
    why_candidate_surfaced: [],
    what_to_verify_manually: [
      'Ask for details about the mentoring circle for ML beginners.',
      'Request portfolio or project links for technical claims.',
    ],
    suggested_follow_up_question:
      'Can you share a specific project from your mentoring circle and describe what participants built?',
    evidence_spans: [
      {
        source: 'motivation_letter_text',
        snippet: 'Created a mentoring circle for beginners in machine learning.',
      },
    ],
    explanation: {
      summary:
        'High merit candidate with notable potential, but confidence is moderate due to evidence density.',
      scoring_notes: {
        potential: 'High due to rapid progress and self-led work.',
        confidence: 'Moderate pending denser evidence in leadership examples.',
      },
    },
  },
  {
    candidate_id: 'cand_006',
    candidate_name: 'Yerzhan Kosherbay',
    program_name: 'Physics',
    scoring_run_id: 'run_20260328_006',
    scoring_version: 'v1.2.0',
    prompt_version: null,
    extraction_mode: 'deterministic_scoring',
    extractor_version: 'llm-extractor-v1',
    llm_metadata: { provider: 'openai-compatible', model: 'llama3.1:8b', latency_ms: 72100 },
    eligibility_status: 'eligible',
    eligibility_reasons: [],
    merit_score: 70,
    confidence_score: 64,
    authenticity_risk: 37,
    recommendation: 'insufficient_evidence',
    review_flags: ['low_evidence_density', 'insufficient_evidence'],
    merit_breakdown: {
      potential: 75,
      motivation: 69,
      leadership_agency: 72,
      experience_skills: 66,
      trust_completeness: 65,
    },
    feature_snapshot: {
      motivation_clarity: 0.67,
      initiative: 0.65,
      leadership_impact: 0.71,
      growth_trajectory: 0.73,
      resilience: 0.76,
      program_fit: 0.7,
      evidence_richness: 0.47,
      specificity_score: 0.52,
      evidence_count: 0.44,
      consistency_score: 0.68,
      completeness_score: 0.69,
      genericness_score: 0.34,
      contradiction_flag: false,
      docs_count_score: 0.1667,
      portfolio_links_score: 0.0,
      has_video_presentation: false,
      logical_source_groups_present: 2,
      material_support_score: 0.41,
      polished_but_empty_score: 0.29,
      cross_section_mismatch_score: 0.06,
      authenticity_risk_raw: 0.37,
      ai_detector_probability: 0.44,
      ai_detector_applicable: true,
      excluded_sensitive_fields_count: 0,
    },
    semantic_rubric_scores: {
      leadership_potential: 56,
      growth_trajectory: 60,
      motivation_authenticity: 54,
      authenticity_groundedness: 51,
      hidden_potential: 53,
    },
    top_strengths: ['Good resilience signal and stable growth trend'],
    main_gaps: ['Impact examples need stronger quantified outcomes'],
    uncertainties: ['Program fit might improve with clearer specialization intent'],
    authenticity_review_reasons: [],
    ai_detector: {
      enabled: true,
      applicable: true,
      language: 'en',
      probability_ai_generated: 0.44,
      provider: 'huggingface-local',
      model: 'desklib/ai-text-detector-v1.01',
      note: 'ok',
    },
    committee_cohorts: ['Low evidence density'],
    why_candidate_surfaced: [],
    what_to_verify_manually: [
      'Request specific competition results and dates.',
      'Ask for quantified outcomes from resilience examples.',
    ],
    suggested_follow_up_question:
      'Can you describe a specific competition failure and exactly what you changed before your next attempt?',
    evidence_spans: [
      {
        source: 'motivation_questions',
        snippet: 'Repeatedly improved competition results after failed attempts.',
      },
    ],
    explanation: {
      summary:
        'Candidate has acceptable merit and potential, but evidence density limits confidence.',
      scoring_notes: {
        potential: 'Moderately high with visible growth trajectory.',
        confidence: 'Moderate due to sparse concrete evidence.',
      },
    },
  },
  {
    candidate_id: 'cand_007',
    candidate_name: 'Aigerim Kurmangali',
    program_name: 'Cybersecurity',
    scoring_run_id: 'run_20260328_007',
    scoring_version: 'v1.2.0',
    prompt_version: null,
    extraction_mode: 'deterministic_scoring',
    extractor_version: 'llm-extractor-v1',
    llm_metadata: { provider: 'openai-compatible', model: 'llama3.1:8b', latency_ms: 66480 },
    eligibility_status: 'conditionally_eligible',
    eligibility_reasons: ['missing_required_materials_documents'],
    merit_score: 67,
    confidence_score: 58,
    authenticity_risk: 29,
    recommendation: 'invalid',
    review_flags: ['missing_required_materials', 'eligibility_gate'],
    merit_breakdown: {
      potential: 79,
      motivation: 77,
      leadership_agency: 61,
      experience_skills: 58,
      trust_completeness: 52,
    },
    feature_snapshot: {
      motivation_clarity: 0.76,
      initiative: 0.73,
      leadership_impact: 0.57,
      growth_trajectory: 0.74,
      resilience: 0.68,
      program_fit: 0.79,
      evidence_richness: 0.51,
      specificity_score: 0.56,
      evidence_count: 0.49,
      consistency_score: 0.62,
      completeness_score: 0.48,
      genericness_score: 0.31,
      contradiction_flag: false,
      docs_count_score: 0.1667,
      portfolio_links_score: 0.0,
      has_video_presentation: false,
      logical_source_groups_present: 2,
      material_support_score: 0.38,
      polished_but_empty_score: 0.25,
      cross_section_mismatch_score: 0.04,
      authenticity_risk_raw: 0.29,
      ai_detector_probability: 0.31,
      ai_detector_applicable: true,
      excluded_sensitive_fields_count: 1,
    },
    semantic_rubric_scores: {
      leadership_potential: 50,
      growth_trajectory: 58,
      motivation_authenticity: 62,
      authenticity_groundedness: 56,
      hidden_potential: 60,
    },
    top_strengths: ['Strong motivation for cybersecurity specialization'],
    main_gaps: ['Mandatory eligibility requirement not satisfied'],
    uncertainties: ['Can be reconsidered once missing certificate is provided'],
    authenticity_review_reasons: [],
    ai_detector: {
      enabled: true,
      applicable: true,
      language: 'en',
      probability_ai_generated: 0.31,
      provider: 'huggingface-local',
      model: 'desklib/ai-text-detector-v1.01',
      note: 'ok',
    },
    committee_cohorts: ['Missing materials', 'Eligibility gate active'],
    why_candidate_surfaced: [],
    what_to_verify_manually: ['Follow up on missing required documents.'],
    suggested_follow_up_question:
      'Can you provide the missing required documents to complete your application?',
    evidence_spans: [
      {
        source: 'motivation_letter_text',
        snippet: 'Describes clear specialization path in defensive security.',
      },
    ],
    explanation: {
      summary:
        'Merit is moderate, but candidate is currently ineligible due to missing required documents.',
      scoring_notes: {
        confidence: 'Lower due to incomplete document package.',
        authenticity_risk: 'Low risk but incomplete submission limits assessment.',
      },
    },
  },
  {
    candidate_id: 'cand_008',
    candidate_name: 'Madina Akhmetova',
    program_name: 'Business Analytics',
    scoring_run_id: 'run_20260328_008',
    scoring_version: 'v1.2.0',
    prompt_version: null,
    extraction_mode: 'deterministic_scoring',
    extractor_version: 'llm-extractor-v1',
    llm_metadata: { provider: 'openai-compatible', model: 'llama3.1:8b', latency_ms: 51930 },
    eligibility_status: 'eligible',
    eligibility_reasons: [],
    merit_score: 76,
    confidence_score: 70,
    authenticity_risk: 24,
    recommendation: 'standard_review',
    review_flags: [],
    merit_breakdown: {
      potential: 74,
      motivation: 79,
      leadership_agency: 71,
      experience_skills: 75,
      trust_completeness: 78,
    },
    feature_snapshot: {
      motivation_clarity: 0.78,
      initiative: 0.69,
      leadership_impact: 0.66,
      growth_trajectory: 0.7,
      resilience: 0.72,
      program_fit: 0.81,
      evidence_richness: 0.68,
      specificity_score: 0.64,
      evidence_count: 0.63,
      consistency_score: 0.77,
      completeness_score: 0.8,
      genericness_score: 0.2,
      contradiction_flag: false,
      docs_count_score: 0.5,
      portfolio_links_score: 0.25,
      has_video_presentation: true,
      logical_source_groups_present: 3,
      material_support_score: 0.65,
      polished_but_empty_score: 0.14,
      cross_section_mismatch_score: 0.02,
      authenticity_risk_raw: 0.24,
      ai_detector_probability: 0.15,
      ai_detector_applicable: true,
      excluded_sensitive_fields_count: 0,
    },
    semantic_rubric_scores: {
      leadership_potential: 60,
      growth_trajectory: 58,
      motivation_authenticity: 66,
      authenticity_groundedness: 64,
      hidden_potential: 52,
    },
    top_strengths: ['Good trust/completeness and balanced profile'],
    main_gaps: ['Potential score could improve with stronger growth evidence'],
    uncertainties: [],
    authenticity_review_reasons: [],
    ai_detector: {
      enabled: true,
      applicable: true,
      language: 'en',
      probability_ai_generated: 0.15,
      provider: 'huggingface-local',
      model: 'desklib/ai-text-detector-v1.01',
      note: 'ok',
    },
    committee_cohorts: ['Balanced low-risk candidate'],
    why_candidate_surfaced: [],
    what_to_verify_manually: ['Confirm referenced business analytics project outcomes.'],
    suggested_follow_up_question:
      'What specific analytical methods did you apply in your business project and what decisions did they inform?',
    evidence_spans: [
      {
        source: 'application_form',
        snippet: 'All required fields and references are filled and consistent.',
      },
    ],
    explanation: {
      summary: 'Solid balanced candidate with strong trust and adequate merit.',
      scoring_notes: {
        confidence: 'High due to complete and consistent submission package.',
        recommendation: 'Standard review path due to balanced profile with low risk.',
      },
    },
  },
]
